name: Add contributors to readme

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Add contributors to readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.3
        with:
          is_protected: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
